ALTER SESSION SET "_oracle_script"=true;

ALTER USER SCOTT ACCOUNT UNLOCK;
ALTER USER SCOTT IDENTIFIED BY TIGER;

CREATE USER SCOTT IDENTIFIED BY TIGER;
GRANT CREATE SESSION TO SCOTT;
GRANT CREATE TABLE TO SCOTT;