SELECT *
FROM STUDENT;

SELECT --GRADE,
AVG(DECODE(GRADE, 1, WEIGHT)) "1",
AVG(DECODE(GRADE, 2, WEIGHT)) "2",
AVG(DECODE(GRADE, 3, WEIGHT)) "3",
AVG(DECODE(GRADE, 4, WEIGHT)) "4"
FROM STUDENT;
--GROUP BY GRADE;

SELECT DEPTNO, NAME
FROM EMP2
WHERE DEPTNO = '1008';