SELECT *
FROM PROFESSOR;

SELECT JOB, CEIL(AVG(SAL))
FROM EMP
GROUP BY JOB;

SELECT GRADE, AVG(WEIGHT)
FROM student
GROUP BY GRADE;

SELECT GRADE, DECODE(GRADE, 1, WEIGHT),
DECODE(GRADE, 2, WEIGHT),
DECODE(GRADE, 3, WEIGHT),
DECODE(GRADE, 4, WEIGHT)
FROM STUDENT;